## Meta-Visualization Framework for Spatiotemporal Analytics:
### From Data Generation to Advanced Visualization on Maps

## **Stage 2: Data Integration tools**

This notebook is dedicated to highlight the main technical aspects related to data integration through our framework.

As discussed in our paper, the data integration can be summarized as follows:

1. Input: a set of heterogeneous cleaned datasets
2. Output: a target database schema or GIS
3. Process: Defining ETL jobs to link data from the input datasets to the target schema.



---
## 1. **Input**

Let us start by displaying a dataset from Stage 1, climats_types.csv for instance, which corresponds to the extracted soil property from soil.png map scan.

In [9]:
import pandas as pd
import numpy as np
url = "https://raw.githubusercontent.com/AnonymAuthors2025/Revised_Meta_Visualization/main/Stage%202/climats_types.csv"
df = pd.read_csv(url)
df

,Unnamed: 0,latitude,longitude,color,most similar,type
0,0,19.0,-8.1,"(240, 242, 227)","(255, 245, 208)",ARID
1,1,19.0,-7.6,"(232, 242, 220)","(255, 245, 208)",ARID
2,2,19.0,-7.1,"(242, 239, 233)","(255, 245, 208)",ARID
3,3,19.0,-6.6,"(242, 239, 233)","(255, 245, 208)",ARID
4,4,19.0,-6.1,"(240, 238, 231)","(255, 245, 208)",ARID
...,...,...,...,...,...,...
1633,1633,38.0,10.4,"(183, 210, 245)","(168, 253, 227)",SUB HUMID
1634,1634,38.0,10.9,"(183, 210, 245)","(168, 253, 227)",SUB HUMID
1635,1635,38.0,11.4,"(183, 210, 245)","(168, 253, 227)",SUB HUMID
1636,1636,38.0,11.9,"(183, 210, 244)","(168, 253, 227)",SUB HUMID
1637,1637,38.0,12.4,"(142, 144, 160)","(88, 211, 150)",HUMID

---
## 2. **Output**

Let us take as example a relational model, which is the most popular, and simplest way to process structured data. We can choose a relational data warehouse which is the most suitable type for data analytics with big data involving many dimesions.

An example of integrated data is given in my_database.db :

In [ ]:
import sqlite3
# Connect to the database
conn = sqlite3.connect('my_database.db')  # Replace with your DB file
cursor = conn.cursor()

In [ ]:
df = pd.read_sql_query("SELECT * FROM crop", conn)

In [ ]:
df

,Crop,Ar,Fr,Climate,Loam,Silt,Sand,Water,Months,Temp_Min,...,Rainfall_min mm_year,Rainfall_max,Farming,Veg,Fruit,Indust,Med,Agro,Weeks,Observation
0,Alfalfa,البرسيم,Luzerne,Temperate,✓,✓,✓,High,"March, April, May, June",-5,...,500,800,1.0,NaN,NaN,NaN,NaN,1.0,6w-8w,"6-8 weeks for the first harvest, subsequent ha..."
1,Almonds,اللوز,Amandes,Mediterranean,✓,None,None,Moderate to High,"February, March, April",-5,...,600,1000,NaN,NaN,NaN,NaN,NaN,1.0,5y-6y,"5-6 years to reach full production, first harv..."
2,Aloe Vera,صبار,Aloè Vera,Arid,✓,✓,None,Low,Year-round,10,...,400,600,NaN,NaN,NaN,NaN,1.0,NaN,2y-3y,2-3 years to reach maturity and start producin...
3,Apples,التفاح,Pommes,Temperate,✓,✓,✓,Moderate to High,"September, October, November",-2,...,600,1000,NaN,NaN,1.0,NaN,NaN,1.0,2y-5y,2-5 years to produce fruit after planting
4,Apricot,مشمش,Abricot,Temperate,✓,✓,None,Moderate to High,"January, February, March",-2,...,600,1000,NaN,NaN,1.0,NaN,NaN,1.0,3y-4y,3-4 years to start producing fruit after planting
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
100,Valerian,الناردين,Valériane,Temperate,✓,✓,✓,Moderate,"April, May, June",15,...,500,800,NaN,NaN,NaN,NaN,1.0,NaN,2y-3y,2-3 years to reach maturity for harvest
101,Walnuts,الجوز,Noix,Temperate,✓,None,None,Moderate to High,"February, March, April, September",-15,...,600,1500,NaN,NaN,NaN,NaN,NaN,1.0,4y-7y,4-7 years to start producing nuts after planting
102,Watermelons,بطيخ أحمر,Pasteques,Tropical,✓,✓,✓,High,"April, May, June",20,...,500,800,NaN,NaN,1.0,NaN,NaN,NaN,80d-100d,80-100 days from planting to harvest
103,Wheat,قمح,Blé,Temperate,✓,✓,✓,Moderate,"September, October, November",10,...,300,600,1.0,NaN,NaN,1.0,NaN,1.0,90d-120d,Approximately 90-120 days from planting to har...
104,Zucchinis,كوسا,Courgettes,Temperate,✓,✓,✓,Moderate to High,"May, June, July",20,...,500,800,NaN,1.0,NaN,NaN,NaN,NaN,6w-8w,6-8 weeks from planting to harvest

This is one example of a table filled from our extracted data in Stage 1.



---

## 3. **Process**

Data integration is implemented through ETL (Extract, Transform, Load) or ELT pipelines, optimized for geospatial and tabular data workflows.

**Key Tools & Platforms**

```
+-------------+------------------------+-------------------------------+
|    Tool     |          Type          |         Specialization        |
+-------------+------------------------+-------------------------------+
| Talend      | Open-source/Enterprise | End-to-end data integration   |
| Pentaho     | Enterprise             | Business analytics focus      |
| GeoKettle   | Open-source            | Geospatial ETL                |
| Apache NiFi | Open-source            | Real-time dataflows           |
+-------------+------------------------+-------------------------------+

```


**Supported Data Systems**
1. Relational: PostgreSQL (+PostGIS), MySQL

2. NoSQL: MongoDB (geospatial queries), Cassandra

3. Cloud: BigQuery, Snowflake, AWS Redshift

4. Streaming: Kafka, AWS Kinesis

**Implementation Example (Python Alternative)**

For lightweight integration without dedicated ETL tools:

```
# GeoPandas + SQLAlchemy ETL  
import geopandas as gpd  
from sqlalchemy import create_engine  

# Extract  
gdf = gpd.read_file("climate_data.geojson")  

# Transform  
gdf["normalized_temp"] = (gdf["temperature"] - gdf["temperature"].mean()) / gdf["temperature"].std()  

# Load to PostGIS  
engine = create_engine("postgresql://user:pass@localhost:5432/gis_db")  
gdf.to_postgis("climate_metrics", engine, if_exists="replace")  
```

**Workflow Stages**

1. Extract

    - Source: APIs (REST, GraphQL), IoT streams, legacy databases

    - Formats: GeoJSON, Parquet, NetCDF

3. Transform:

    - Geospatial: Reprojection (EPSG codes), topology checks

    - Tabular: Schema alignment, outlier handling

3. Load

    - Validation: Great Expectations framework

    - Destinations: Data warehouses/lakes with versioning (e.g., Delta Lake)